project:
  type: book
  output-dir: ./publish

book:
  title: "DeSci"
  language: "en"
  author: "Guangtao Zhang"
  reader-mode: true
  chapters:
    - index.qmd

    - part: julia-graph.qmd
      #
chapters:
      #
  - haskell.qmd


format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: ctexbook
    pdf-engine: tectonic


execute:
  warning: false

biliography: references.lib
